//ALL ROBOT PORT DEFINITIONS

//Drivetrain
#define FRONT_LEFT_MOTOR 13
#define FRONT_RIGHT_MOTOR 11
#define BACK_LEFT_MOTOR 2
#define BACK_RIGHT_MOTOR 1

//Arm
#define ARM_MAX_LIMIT_SWITCH 'H'
#define ARM 12